// <auto-generated />
namespace MyTunesList.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class unabletoupdatedatabasetomatchthecurrentmodelbecausetherearependingchangesandautomaticmigrationisdisabled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unabletoupdatedatabasetomatchthecurrentmodelbecausetherearependingchangesandautomaticmigrationisdisabled));
        
        string IMigrationMetadata.Id
        {
            get { return "202109251313014_unable to update database to match the current model because there are pending changes and automatic migration is disabled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
